apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-replicas
  labels:
    app : nginx
    env : testing
spec:
  replicas: 2
  selector:
    matchLabels:
      project: sf
  template:
    metadata:
      labels:
        project: sf 
    spec:
      containers:
        - name: websrv1
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-web-service
  labels:
    env: testing
spec:
  selector:
    project: sf
  ports:
    - name      : app-lostner
      protocol  : TCP
      port      : 8888  #Listn port
      targetPort: 80  # Port on Pods
  type: LoadBalancer
