---
- hosts: all
  become: yes
  become_user: root
  tasks:

  - name: Download file and force basic auth
    local_action: get_url url=https://docs.projectcalico.org/manifests/calico.yaml dest=./

  - name: install network plugin
    become: no
    local_action: command kubectl apply -f ./calico.yaml
